<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
$lang = array(
    'page_where' => "位置：",
    'page_where_start' => "首页",
    'page_where_middle' => "充值管理",
    'page_where_list' => "充值列表",
    'page_where_add' => "添加充值",
    'page_where_edit' => "修改操作",
    'page_title' => "充值顶部标题",
    'charging_online' => "在线充值",
    'charging_offline' => "线下充值",
    'charging_cancel' => "取消充值",
    'todo' => "操作",
    'add' => "添加",
    'edit' => "修改",
    'del' => "删除",
    'upload' => "上传",
    'detial' => "详情",
    'addson' => "添加子类",
    'yes' => "是",
    'no' => "否",
    'all' => "全部",
    'chonese' => "请选择",
    'no_parents' => "没有父级",
    'parent_name' => "父级名称",
    'error_uniqu' => "该信息已经存在，不能重复添加",
    'error_unknow' => "未知错误",
    'error_requer' => "信息没有填写完整",
    'error_params' => "参数错误",
    'error_defalut_info' => "获取初始信息失败",
    'delete_notice' => "你确定要删除此条信息吗？",
    'delete_has_son' => "删除失败，该分类下还有子项目",
    'save success' => "保存成功",
    'save faild' => "保存失败",
    'delete success' => "删除成功",
    'search' => "搜索",
    'keyword' => "关键字",
    'day' => "天",
    'month' => "月",
    'year' => "年",
    'id' => "ID",
    'charging_ns' => "充值编号",
    'uid' => "用户ID",
    'uname' => "用户名",
    'amount' => "充值总额",
    'pay_type' => "支付类型",
    'discription'=>"简单说明",
    'status' => "当前状态",
    'create_time' => "提交时间",
    'update_time' => "最后操作时间",
    'do_uid' => "操作人ID",
    'status_0' => "已提交",
    'status_1' => "待审核",
    'status_2' => "充值成功",
    'status_3' => "充值失败",
    'status_4' => "已取消",
);
?>
