<?php

$lang = array(
    'page_where' => "位置：",
    'page_where_start' => "首页",
    'page_where_middle' => "项目申请管理",
    'page_where_list' => "项目申请列表",
    'page_where_add' => "添加项目申请",
    'page_where_edit' => "修改项目申请",
    'page_title' => "项目申请管理标题",
    'error_unknow' => "未知错误",
    'error_requer' => "信息没有填写完整",
    'error_params' => "参数错误",
    'error_unique' => "该数据已经存在",
    'delete_notice' => "你确定要删除此条信息吗？",
    'add_sucess' => "添加成功",
    'edit_sucess' => "修改成功",
    'all'=>"全部",
    'button'=>"待审核",
    'passed'=>"通过",
    'unpassed'=>"未通过",
    'pass'=>"通过",
    'unpass'=>"不通过",
    'add' => "添加",
    'del' => "删除",
    'edit' => "修改",
    'detial' => "详情",
    'upload' => "上传",
    'search'=>"搜索",
    'excel'=>"导出EXC",
    'todo'=>"操作",
    'id'=>"自增ID",
    'project_name'=>"项目名称",
    'username'=>"姓名",
    'gander'=>"性别",
    'celphone'=>"联系电话",
    'wechat'=>"微信账号",
    'sina'=>"新浪帐号",
    'my_description'=>"自我描述",
    'pro_description'=>"项目描述",
    'status'=>"当前状态",
    'addtime'=>"添加时间",
    'passtime'=>"处理时间",
    'uid'=>"用户ID",
);
?>
