<?php

$lang = array(
    'page_where' => "位置：",
    'page_where_start' => "首页",
    'page_where_middle' => "系统设置",
    'page_where_list' => "设置列表",
    'page_where_add' => "添加操作",
    'page_where_edit' => "修改操作",
    'page_title' => "系统设置顶部标题",
    'id' => "ID",
    'titel' => "标题",
    'actionname' => "方法名",
    'controller' => "控制器",
    'parent_id' => "父级ID",
    'sult' => "排序",
    'addtime' => "添加时间",
    'adder' => "添加人员",
    'is_del' => "是否删除",
    'todo' => "操作",
    'add' => "添加",
    'edit' => "修改",
    'del' => "删除",
    'detial' => "详情",
    'addson' => "添加子类",
    'yes' => "是",
    'no' => "否",
    'no_parents' => "没有父级",
    'parent_name' => "父级名称",
    'error_unknow'=>"未知错误",
    'error_requer'=>"信息没有填写完整",
    'error_params'=>"参数错误",
    'delete_notice'=>"你确定要删除此条信息吗？",
    'delete_has_son'=>"删除失败，该分类下还有子项目",
);
?>
