<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$lang = array(
    'page_where' => "位置：",
    'page_where_start' => "首页",
    'page_where_middle' => "广告短信管理",
    'page_where_list' => "广告短信列表",
    'page_where_detial' => "广告短信详情",
    'page_where_add' => "添加广告短信",
    'page_where_edit' => "修改广告短信",
    'page_title' => "广告短信管理标题",
    'error_unknow' => "未知错误",
    'error_requer' => "信息没有填写完整",
    'error_params' => "参数错误",
    'error_product_params' => "广告短信参数错误",
    'error_unique' => "该数据已经存在",
    'add_sucess' => "添加成功",
    'edit_sucess' => "修改成功",
    'del_conform'=>"你确定要删除此信息？",
    'reset_conform'=>"你确定要重置并重新发送此信息？",
    'get_start_array_filed'=>"没有获取的到对应的数据信息，操作失败！",
    'search'=>"查询",
    'pass'=>"通过",
    'all'=>"全部",
    'add' => "添加",
    'del' => "删除",
    'edit' => "修改",
    'reset'=>"重置",
    'detial' => "详情",
    'tender'=>"项目动态",
    'introduce'=>"项目介绍",
    'buyitems'=>"购买子项",
    'invest'=>"投资记录",
    'todo'=>"操作",
    'recover'=>"恢复",
    'no'=>"未发送",
    'yes'=>"已发送",
    'used'=>"已使用",
    'postwaiting'=>"上传等待",
    'username_no'=>"手机号码提示",
    'username_notice'=>"多个手机号码用英文状态下的逗号(',')隔开；全站发送输入all。",
    'content_no'=>"内容提示",
    'content_notice'=>"短信内容字数控制在100字以内",
    'id'=>"ID",
    'user_id'=>"用户ID",
    'user_name'=>"用户名称",
    'cellphone'=>"手机号码",
    'content'=>"信息内容",
    'status'=>"当前状态",
    'trytimes'=>"尝试次数",
    'creattime'=>"创建时间",
    'sendtime'=>"发送时间",
);
?>