<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

$lang = array(
    'page_where' => "位置：",
    'page_where_start' => "首页",
    'page_where_middle' => "产品管理",
    'page_where_list' => "产品列表",
    'page_where_detial' => "产品详情",
    'page_where_add' => "添加产品",
    'page_where_edit' => "修改产品",
    'page_title' => "产品管理标题",
    'error_unknow' => "未知错误",
    'error_requer' => "信息没有填写完整",
    'error_params' => "参数错误",
    'error_unique' => "该数据已经存在",
    'delete_notice' => "你确定要删除此条信息吗？",
    'recover_notice'=> "你确定要恢复此条信息吗？",
    'pass_notice'=> "你确定要通过此条信息吗？",
    'add_sucess' => "添加成功",
    'edit_sucess' => "修改成功",
    'search'=>"查询",
    'pass'=>"通过",
    'all'=>"全部",
    'add' => "添加",
    'del' => "删除",
    'edit' => "修改",
    'detial' => "详情",
    'tender'=>"项目动态",
    'introduce'=>"项目介绍",
    'buyitems'=>"购买子项",
    'invest'=>"购买记录",
    'todo'=>"操作",
    'recover'=>"恢复",
    'replay'=>"评论",
    'yes'=>"是",
    'no'=>"否",
    'upload'=>"上传",
    'no_type'=>"没有分类",
    'please_choose_province_first'=>"请先选择省份",
    'id'=>"ID",
    'title'=>"产品名称",
    'title_salt'=>"产品口号",
    'product_type'=>"产品分类",
    'province'=>"省份",
    'city'=>"城市",
    'type_name'=>"分类名称",
    'province_name'=>"省份名称",
    'city_name'=>"城市名称",
    'banner'=>"产品广告图",
    'image_url'=>"产品封面",
    'video'=>"视频地址",
    'source_video'=>"视频源地址",
    'amount'=>"目标金额(元)",
    'support_amount'=>"已支持额",
    'support_times'=>"支持次数",
    'views'=>"查看次数",
    'starttime'=>"开始时间",
    'endtime'=>"结束时间",
    'days'=>"上线时长(天)",
    'user_id'=>"发布人",
    'discription'=>"内容概要",
    'content'=>"产品详情",
    'product_loading'=>"进展数目",
    'repay'=>"评论次数",
    'seo_title'=>"优化标题",
    'seo_keyword'=>"优化关键字",
    'seo_discription'=>"优化描述",
    'addtime'=>"添加时间",
    'is_effect'=>"审核状态",
    'is_rem'=>"是否推荐",
    'salt'=>"排序",
    'is_del'=>"是否删除",
    'is_success'=>"默认成功"
);
?>